layout_spectrum: 0.8532821
color:
  saturation: 0.9498208
  lightness: 0.5842294
  brandStrength: 0.08981929
  brandColors:
    - '#F4F5F9'
    - '#090504'
    - '#4B4829'
    - '#E51213'
    - '#D56C1F'
  rhythmicContrast: 0.8419092
typography_spectrum: 0.1164875
name: www.islandgirl.clothing
